name: focus_mate
description: "A Flutter productivity app for focus management, task tracking, and app blocking."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  block_app: ^0.0.1

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  cloud_functions: ^5.1.0

  # Other
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.0

  # State Management
  flutter_riverpod: ^2.4.0

  # Schedule Import â€” AI + Image Picking
  firebase_ai: ^2.3.0
  image_picker: ^1.1.2

  # Unique IDs
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/button_bg.png
